language: go
sudo: false

env:
    global:
        - secure: "ITDntBhrsGK5buug86PEPwk9ez34lqJoKUo0hf1IjoQXq/J30sQ/SvXjyah9gZXXuP//sJE7s67x9x26zkXAST8DSQa0sluo7EkIhaQ86V8l5ax24CM+1MlgtChsPN81S8zVK5OW25IwJhNJf5DdXrirFuYUlyYnZDuajvlbFeZvYdTUUdSP707nLi5m31Lx+TkvXHdiULsEm6KD47YBC2PiNHSfVssXgZd73ilXhX99gyxXYlmsKWi5jrMeGwumbDVfl9mDHv/PO0exd4nyWzxUxzulIYdx7eG2o5r1hCSgYSbWV6rPyON9+tnQhdDsrYeOiKLIXU6mXLaNtA73ElctQuxzuXycsXHxFZdEzKk4NyhrTJBGbu3HmUmZRO7YPNJCHeVAyDXv9Vz1zppcdRwoZLeCHK8uZUMwmcUdOGQ4irWjRePX90Dj8SCQowH5dkr8yFd1V3Ztf+xVkNz4iU4u8WYx6aBc+3TZKrZa3JOOKtgx0mmyP4dMhRHj0tT1Iv4LDXhZSjFTRwAyVerxVqUgI6fylmg4r/emNUhhN7pQuxoccjH6rPhT9VOB/tUPdI6TFbl/l7v/PHOZ2bh35R+jhQII0VPG7Lp5DBdcs23tU3EOBAlflUcs3wchgr5bkF24gVOptL7KXnPUvtm9Zghy4576CofxUT/Di0/5L+M="
        - secure: "XuydfoJQhG42ztSc33v9K74hvUY0r1vZS4mwp/Hc9xK6vmkmfM7xhMCSZb+g56MTmsCDF0c2/iULR5vjqSQX1rYZyHfhao0bhSSFeJxciFsik6NSZTNs71snoTe6KLvaVZG8om4Gk7sQSzNB6mTOc/iuM+DA5wMSYeZYLRlvP5O0sXAjJZk8GP2I76UQgLht/svS877e/uOAkyw0b/arq+1uxEHad81QpvZoTJ4o6uvfZTD5iKbikrj0u9yYsuDwRLNdzwInij96srjlxTyTWOwoIZEK31dg39A08mUjCU3X6Z+o7Nv2bV4JB3ShJCHn7EQqhh0gkNKXqJq4Y5Oa8HTeOekkmWDXpMI+KqKSGri3ckZ31eo3AauEF0VQ7mo4g82acCx7PN8OwYAXs1aTTEfhhbI51aw2ik8xSqPE7yyWDars0oamz0wLRWIMfGK1/TdWDGLlA84yx794zJrpem4FXB5QFRHdwizesdMc3rZN/KVCmz3mDjn1Dl13egZpjIIarExRVqroTponmVzOz5PmLhDjXD+Gmi/QqTOjjBp/LGwaWe+6WFYEVFQxXv8wpRwL/Q5ayBpVr3y+waxO7j6qjHdCDWqMocB4X41UpRJ187GZD/q/9WwVbq+mzct4EEMqUmQLRvoiYjdYGSYrKQc57MdJYRZ9rLmELlxKpE4="
matrix:
  include:
    - go: 1.x
      env: LATEST=true

before_install:
    # Make sure the build script is executable
    - chmod +x scripts/build-all.sh
    - chmod +x scripts/discord-notify.sh

install:
    - # skip

script:
    - ./scripts/discord-notify.sh started $DISCORD_WEBHOOK
    - go get -t -v ./...
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -v -race ./...
    # Only build binaries from the latest Go release.
    - if [ "${LATEST}" = "true" ]; then scripts/build-all.sh; fi

after_success:
    - ./scripts/discord-notify.sh success $DISCORD_WEBHOOK

after_failure:
    - ./scripts/discord-notify.sh failure $DISCORD_WEBHOOK

deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: "Vk5cvBpwLB8+bKeccgrUE7Qc4t4lHX0Rg9Rag8UTJugtvG3t8wt7SaYRDWJ9deqbkn487F7SrDY64FZLU3w47mMViJ2MK5gbqYJR4nIzixig4WwFJEtp3HQmfez2FmPuIOS+WptEe9L0GZSw7B8UP6yDCTDSPr3yY6sFMNl0EZgz3cFV0oVI44BjyyUCxEpXKY9G4bbVsozTmkIHM701q66vE53z4mwqc1VjNuI/WeUATJT/D6O5DXr+d+kaLasuR7n6SkfIxQS/J7VSYbslUdT4D/OKswXXwnd+o+029qvv4KCYgkhxAlKc2k3jeR+TQDBMExaIgZkOgPQ3fa0QM4BUtT5APFhsAFZ/850GQYQ7fz1eC0A42J9n56uLsIVwsH3W2v1J3aw5m0H71bWHAxGROa1uXaez29i7MxkM7wDA6rgu+Hs8g1Gkny+nBwSUjYW+1VAU+SoSJLxpDGvbFX5FE00fWjZyvVnnc5zmr0hyv+H7ODv1R3r1qzndiBO7nU1CfpOK8Tt+kPx5oPiLU+F6NBlH2AbdCK0jIadOnVp53So07vqo9cslR4eP6taVVn2do1QsY2uuXOfaLuu60nr51zcJQwAO8ihEilZJn3UMUeBUQaRPZX20xbZM7R6kTeowCoJmPRyDK6A7BfVRrCncmVIyDLjEJz1ikbHDJVI="
    file:
        - builds/gello-windows-amd64.exe
        - builds/gello-windows-386.exe
        - builds/gello-linux-amd64
        - builds/gello-darwin-amd64
        - builds/gello-linux-386
    on:
        repo: TGRHavoc/gello
        tags: true
        condition: $LATEST = true